### PR TITLE
case statement for operatingsystem, set version from this

### PR DESCRIPTION
**Pull request by adamcstephens**
Fixes bfraser/puppet-grafana#42

### CODE REVIEW

**Comment by joshbeard** [comment]
Rather than using `$::operatingsystem`, can we get away with `$::osfamily` here to support other EL type systems (e.g. Scientific)?

**Comment by bfraser** [comment]
The ```version``` parameter is also referenced by the 'archive' install method, which can be used regardless of the operating system. Perhaps we can default to version 2.1.0 and only set it to 2.1.0-1 in a conditional as part of the 'package' and 'repo' install methods? I'm open to suggestions.

**Comment by adamcstephens** [comment]
I agree osfamily is better. I'll change it tomorrow.

**Comment by bfraser** [comment]
Actually, looking at this further, this change would break the ```package_source``` parameter as the URL includes a reference to ```version```. I've actually [hardcoded](https://github.com/bfraser/puppet-grafana/blob/master/manifests/init.pp#L78) the '-1' in ```init.pp```.

**Comment by adamcstephens** [comment]
The last commit should resolve the discussed issues.

**Comment by bfraser** [comment]
This will still prevent the archive install method from working, as it [references](https://github.com/bfraser/puppet-grafana/blob/master/manifests/init.pp#L66) the ```version``` parameter too.

How can we implement this while still permitting the archive method to work, as that should be a fallback for users that are either not using Debian or RedHat based systems, or choose to not use packages for some reason?

Along those lines, I don't know that we should [fail outright](https://github.com/covermymeds/puppet-grafana/blob/5e877ba79a39e50fa00830322482b3dfac9f516a/manifests/params.pp#L23) if the target system is not one of those OS families.

**Comment by adamcstephens** [comment]
Let me know if you see any other issues.

**Comment by bfraser** [comment]
This looks good @adamcstephens thanks for the contribution!

**Pull request merged**
