### PR TITLE
Add "repo" install_method.

### PR DESCRIPTION
**Pull request by alienth**
Allows grafana to be installed out of the repos configured on your OS.

### CODE REVIEW

**Comment by jbehrends** [comment]
+1

I can't use this module at the moment because the RPM in our internal repo won't be used.

**Comment by adamcstephens** [comment]
Are there any plans to merge this? Grafana has repos for both .deb and .rpm based systems, so its a bit non-standard to fetch it and install it manually...

**Comment by rplessl** [comment]
Improved repo enhancement as a pull request here: https://github.com/bfraser/puppet-grafana/pull/34

**Comment by bfraser** [comment]
Closing as this functionality was implemented in #34

**Pull request closed without merging**
